### ISSUE TITLE
Subjection about IotaAPI.getNewAddress() method

### ISSUE THREAD

**Issue by kaonick** [iotaledger/iota-java#113]
1. The method name is get "New" address，but actually is not.(index maybe reused)

2. Another confuse is that if I want to get 2 new address, I will never get it by this method.
See below when get first new address(no any transaction in there) will break.that cause always get the same new address.  
```
        // No total provided: Continue calling findTransactions to see if address was
        // already created if null, return list of addresses
        for (int i = index; ; i++) {

            final String newAddress = IotaAPIUtils.newAddress(seed, security, i, checksum, customCurl.clone());
            final FindTransactionResponse response = findTransactionsByAddresses(newAddress);

            allAddresses.add(newAddress);
            if (response.getHashes().length == 0) {
                break;
            }
        }
```

**Comment by kwek20** [comment]
Thank you for opening this issue, I can see how that is confusing.

I will rename the function to getNextAvailableAddress() and create a new one called generateNewAddresses(int amount). Will that suffice?

**Comment by kaonick** [comment]
That's great.
Thanks to the moon~

**Comment by kwek20** [comment]
Hey @kaonick 

I have made a pull request, could you quickly verify that this what you were expecting?
