### ISSUE TITLE
Release to Maven central

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iota-java#116]
As soon as there is an official release, we want to be able to use the library directly from maven without third party repositories.

**Comment by kwek20** [comment]
@Fabryprog

**Comment by mbe24** [comment]
Is there a release date yet?

**Comment by mbe24** [comment]
As of version `1.0.0-beta1` the library can be used together with Maven and the Jitpack repository, since there are no more special characters in the `artifactId`.

**Comment by Fabryprog** [comment]
Hello boys. There are any news?

**Comment by kwek20** [comment]
@Fabryprog Slow and steady progress sir!
I have discussed it and we will attempt to release the beta2 (and beta3) before the release!
https://issues.sonatype.org/browse/OSSRH-44760

**Comment by kwek20** [comment]
@Fabryprog 
Alright! beta2 is there now. beta3 is awaiting upload.

https://mvnrepository.com/artifact/org.iota/jota-parent?repo=bt-iotaledger

**Comment by Fabryprog** [comment]
@kwek20 sorry but i don't understanding 

I see your package into IOTA repo. It isn't into Maven Central Repo

Is it right?

**Comment by kwek20** [comment]
@Fabryprog Iota beta3 is now available on maven central! Enjoy.
