### ISSUE TITLE
Connecting to testnet

### ISSUE THREAD

**Issue by adonnini** [iotaledger/iota-java#124]
Hi,

I apologize in advance for this question if it's been asked before. I could not find the documentation.

How would the API start-up sequence change if I wanted to connect to the IOTA test network (Mainnet)?

Thank you,

Alex Donnini

**Comment by adonnini** [comment]
Hi,

Is this the code I would use?


    @Before
    public void createApiClientInstance() {
        iotaAPI = new IotaAPI.Builder().port("80").build();
    }

    @Test
    public void shouldCreateIotaApiProxyInstanceWithDefaultValues() {
        iotaAPI = new IotaAPI.Builder().build();
        assertThat(iotaAPI, IsNull.notNullValue());
        assertThat(iotaAPI.getHost(), Is.is("nodes.testnet.iota.org"));
        assertThat(iotaAPI.getPort(), Is.is("80"));
        assertThat(iotaAPI.getProtocol(), Is.is("http"));
    }

**Comment by kwek20** [comment]
Hey @adonnini 
The testnet/mainnet makes little difference for the library side. The node/iri would need to be started different. As long as you connect the library to a testnet node, you are connected to the testnet.

Are you having trouble connecting to a node?

**Comment by adonnini** [comment]
Thanks for the quick response.

I am not having trouble connecting. I am about to try for the first time. I just want to get it right, if at all possible.

Would code like this be correct?

@Before
public void createApiClientInstance() {
    iotaAPI = new IotaAPI.Builder().port("80").build();
}

public void shouldCreateIotaApiProxyInstanceWithDefaultValues() {
    iotaAPI = new IotaAPI.Builder().build();
    assertThat(iotaAPI, IsNull.notNullValue());
    assertThat(iotaAPI.getHost(), Is.is("nodes.testnet.iota.org"));
    assertThat(iotaAPI.getPort(), Is.is("80"));
    assertThat(iotaAPI.getProtocol(), Is.is("http"));
}

Thanks

**Comment by kwek20** [comment]
Unless youre using the confuguration file, you can conenct to the node like this:
`iotaAPI = new IotaAPI.Builder().host("nodes.testnet.iota.org").protocol("http").port("80").build();`

**Comment by adonnini** [comment]
Great! thanks.
