### ISSUE TITLE
IotaAPI#getNewAddress with 'returnAll=true' only return the latest generated address?

### ISSUE THREAD

**Issue by huangfengjing** [iotaledger/iota-java#134]
` @Deprecated
    public GetNewAddressResponse getNewAddress(final String seed, int security, final int index, final boolean checksum, final int total, final boolean returnAll) throws ArgumentException {

       ...
        // If !returnAll return only the last address that was generated
        if (!returnAll) {
            return generateNewAddresses(seed, security, checksum, 0, 1, true);
        } else {
            return generateNewAddresses(seed, security, checksum, 0, 1, false);
        }
       ...
    }`

seems returnAll paramter got a wrong description?

**Comment by kwek20** [comment]
Good catch! those `1` should be `total`, yes. In the meantime, you can call `generateNewAddresses` directly. The function is `Deprecated` and will be removed soon-ish.

If we decide not to remove it in the next version, I will fix the bug,
