### ISSUE TITLE
does "remainderAddress" shoud remove the check sum?

### ISSUE THREAD

**Issue by huangfengjing** [iotaledger/iota-java#135]
https://github.com/iotaledger/iota-java/blob/b2b49f400c0e43626577f5d1f12d0deb18b0ee2c/jota/src/main/java/jota/IotaAPI.java#L1299

If "remainderAddress" got a length of 90, it should remove the checksum to build a bundle entry, or it will throw an exception while signing.

**Comment by kwek20** [comment]
This happens at iota-java/jota/src/main/java/jota/IotaAPI.java:1566
