### ISSUE TITLE
Feature Request: IotaAPICore Builder should support connection and read timeout as parameter

### ISSUE THREAD

**Issue by remmerw** [iotaledger/iota-java#145]
IotaAPICore Builder should also support read timeout and connection timeout as 
configuration parameter for the OkHttpClient.Builder.

Reason: maybe a IRI node is not available, then it takes time to much time, since the expected 
connection exception is raised

**Comment by kwek20** [comment]
Great idea! I will add it in the next pre-release version. Probably in 1 or 2 weeks.

**Comment by kwek20** [comment]
Hey @remmerw, I apologize for the delay.
The feature was added in the account module, and therefor forgotten in the pre-release. 
A new release will be made tomorrow with the `.timeOut(int)` builder method
