### ISSUE TITLE
How can get message from  getTransfer

### ISSUE THREAD

**Issue by xiaocaipi** [iotaledger/iota-java#153]
when I  sendTransfer , user api like
 transfers.add(new Transfer(address, 0, StringUtils.rightPad("SENDFA", 6, '9'), "IOTAJAVASPAM999999999999999"));

but when I use  getTransfer api  like  iotaAPI.getTransfers(TEST_SEED2,1,0,10,false);
there is no "SENDFA"  message in the  response

**Comment by xiaocaipi** [comment]
![image](https://user-images.githubusercontent.com/3810246/55395516-43964680-5574-11e9-84f0-004c20734610.png)

the picture is the debug show the field  in transcation

**Comment by xiaocaipi** [comment]
sorry  I find it  in the signatureFragments  field ,but it will append so many 999 behind my message

**Comment by kwek20** [comment]
Hello @xiaocaipi 
If you still need an example, you can find it here:
https://github.com/iotaledger/iota-java/blob/dev/jota/src/main/java/org/iota/jota/account/event/events/EventReceivedMessage.java#L19

This will take care of the 9's in the end as well.
