### ISSUE TITLE
API timeout set to 5000 seconds ?!

### ISSUE THREAD

**Issue by alon-e** [iotaledger/iota-java#154]
I guess this is a bug, the timeout is set in seconds, and 5000:
https://github.com/iotaledger/iota-java/blob/1aa19d8374411590407784412305545a60db192a/jota/src/main/java/jota/IotaAPICore.java#L109

suppose to be 5000 milli?

**Comment by alon-e** [comment]
related to #145

**Comment by ManuZiD** [comment]
Hi @kwek20 if this is already fixed, please can you close this?
