### ISSUE TITLE
Setter for localPow in IotaAPICore

### ISSUE THREAD

**Issue by remmerw** [iotaledger/iota-java#156]
Feature Request:
new setter function in 
IotaAPICore::localPoW(IotaLocalPoW localPoW)

Reason is simple: 
Connection to a node is already made, then
you can check if node can remotePow (NodeInfo getFeatures)
-> and dependent of the result you can do local PoW or not

**Comment by kwek20** [comment]
Hey @remmerw 

Good idea! Ill have to look at how to implement, since we will need to support multiple nodes in the future.
Ill keep you updated.

**Comment by kwek20** [comment]
This has been implemented on master and can thus be closed!
