### ISSUE TITLE
eclipse : Missing artifact com.sun:tools:jar:1.8

### ISSUE THREAD

**Issue by wonkytonky2** [iotaledger/iota-java#160]
![image](https://user-images.githubusercontent.com/48189056/55984953-f0707200-5c9e-11e9-8c5b-983594a15a44.png)
win 10 
eclipse Version: 2019-03 (4.11.0)
i got java 8 sdk
i cloned project.
i tried many things  adding the jar manualy on some places. 
doesn't seem to work.  looks like a maven thing

**Comment by kwek20** [comment]
Hello @wonkytonky2 

Can you confirm to me that your eclipse is pointing to a JDK (and not a JRE), and that the JDK contains tools.jar?

**Comment by wonkytonky2** [comment]
![image](https://user-images.githubusercontent.com/48189056/56043903-62e45f00-5d3e-11e9-96a0-e24ebafce9ce.png)
I added the tools.jar by myself here . but it still not works . i use JDK though

**Comment by kwek20** [comment]
@wonkytonky2 
Could you clone the following repository, and test if it compiles?
https://github.com/iotaledger/java-md-doclet

In the pom.xml, theres a profiles section on the bottom. Maybe I need to add/change the path for windows.

**Comment by zero24x** [comment]
hello,

@kwek20 i ran into the same error message, i was able to clone the mentioned repo above and compile it (maven clean compile package install), please try to merge the fix you made so we can compile again, thanks!

**Comment by kwek20** [comment]
@zero24x Yes Great! Once i merged the new release for java-md-doclet, it took too long to get picked up by jitpack so i got distracted :D

Ill get on it!
