### ISSUE TITLE
compile is obsolete and has been replaced with implementation

### ISSUE THREAD

**Issue by mtrabelsi** [iotaledger/iota-java#180]
<img width="768" alt="Screenshot 2019-06-18 at 13 35 59" src="https://user-images.githubusercontent.com/7538862/59678991-084c0100-91ce-11e9-9e5e-4cd407d43868.png">

**Comment by kwek20** [comment]
Hey @mtrabelsi, what do you mean with this? Jota does not have any dependencies with scope: compile as far as I can see.

**Comment by ManuZiD** [comment]
@mtrabelsi can you please provide more details on this?

**Comment by ManuZiD** [comment]
I think this is a issue related to the android platform and not to the iota-java client. +1 to close this.

**Comment by kwek20** [comment]
Closed due to no feedback and likely not related
