### ISSUE TITLE
can not send txs

### ISSUE THREAD

**Issue by chenlunyusi** [iotaledger/iota-java#213]
{"error":"entry point failed consistency check: GOITQRCKJWJCCTNQKCDWTUQUWISR9MWAOPDKYIYCRPV9IPDWFPDSTVJZLADZGZQTHNDBXIXISVGDPD999","duration":14}
	at org.iota.jota.connection.HttpConnector.wrapCheckedException(HttpConnector.java:253)
	at org.iota.jota.connection.HttpConnector.getTransactionsToApprove(HttpConnector.java:333)
	at org.iota.jota.IotaAPICore.getTransactionsToApprove(IotaAPICore.java:454)
	at org.iota.jota.IotaAPI.sendTrytes(IotaAPI.java:413)
	at org.iota.jota.IotaAPI.sendTransfer(IotaAPI.java:1298)
	at org.iota.jota.testAPI.HelloWorld.main(HelloWorld.java:40)

Excuse me, when I want to send a transaction on a node that is out of sync, I receive an error.

**Comment by kwek20** [comment]
@chenlunyusi What is the exact code you use to send? Make sure to remove seeds or any other values that are private :)

`entry point failed consistency check` means that we cannot find a path from the entrypoint (lets say a milestone) to a tip. So maybe this node is too much out of date. Why do you want to send something to an out of date node? (This is IRI behaviour by the way, not related to the library)

**Comment by chenlunyusi** [comment]
I want to make some different nodes which could validate the TXs I want to send. So that it is friendly for someone.
It means I want to have a Sharing on IOTA.
I can't find the answer......

**Comment by chenlunyusi** [comment]
I want to make some different nodes which could validate the TXs I want to send. So that it is friendly for someone.
It means I want to have a Sharding on IOTA.
I can't find the answer......

**Comment by kwek20** [comment]
@chenlunyusi Sorry i missed your reply!
If you want some more information about Sharding (which we will have at some point), I reccomend reading this blog: https://medium.com/@hans_94488/scaling-iota-part-1-a-primer-on-sharding-fa1e2cd27ea1

As of now, validating tx can be done using the BundleValidator on iota-java, or just by calling storeTransaction on any node. It will return an error if its wrong.
