### ISSUE TITLE
getTransactionsObjects blocks forever when given an address hash

### ISSUE THREAD

**Issue by eukaryote31** [iotaledger/iota-java#52]
Using v0.9.6:

Passing any address hash (and any non transaction hash probably) to getTransactionsObjects blocks forever (or at least an unacceptably long time). Expected behavior would be to skip invalid entries.

**Comment by pinpong** [comment]
Sorry, i'm not sure if I understand your problem.

**Comment by eukaryote31** [comment]
My code:
```
package eukaryote.test;

import java.util.List;

import jota.IotaAPI;
import jota.model.Transaction;

public class Main {

	public static void main(String[] args) {
		IotaAPI api = new IotaAPI.Builder().host("node.iotasear.ch").port("14265").build();

		System.out.println("api initialized " + api.getNodeInfo().toString());

		List<Transaction> txnobj = api.getTransactionsObjects(new String[] {
				"FL9LKLBPYVKQ9QZBSGENTIDVMOZMFXREVUNWOY9NB9GMFQWKLPDWCJSRUKYCSQVQMNGAQGDKXQ9VAMSNABFUYUOVAD" });
		
		System.out.println(txnobj);
	}

}
```
(Note: my node is configured to only accept connections from my computer)

Node Info Output:
```
api initialized jota.dto.response.GetNodeInfoResponse@7cd62f43[
  appName=IRI
  appVersion=1.4.1.1
  jreVersion=1.8.0_144
  jreAvailableProcessors=2
  jreFreeMemory=293612440
  jreMaxMemory=2863661056
  jreTotalMemory=631767040
  latestMilestone=ZFOIUHXNDIPOZCHBXRLYDGKBZJAZEKIREBYXXGVSBZ9UCWKKBNHBQLNULGK9BFDB9UZKWQMZXCXUZ9999
  latestMilestoneIndex=270540
  latestSolidSubtangleMilestone=ZFOIUHXNDIPOZCHBXRLYDGKBZJAZEKIREBYXXGVSBZ9UCWKKBNHBQLNULGK9BFDB9UZKWQMZXCXUZ9999
  latestSolidSubtangleMilestoneIndex=270540
  neighbors=11
  packetsQueueSize=0
  time=1509925695637
  tips=1243
  transactionsToRequest=40
  duration=0
]
```

What happens: The program runs fine up to the getTransactionsObjects line, and then just freezes. 
When I change the node to `node03.iotatoken.nl`, it works as expected, even though both use IRI 1.4.1.1. Any idea why this happens?

**Comment by pinpong** [comment]
I remember me about a core [bug](https://github.com/iotaledger/iri/issues/126)

**Comment by BerserkerInterpreter** [comment]
Are you sure your node "node.iotasear.ch" (IP address) in the port 14265 is listening (active) currently? You can be aware of it through the making of a telnet with the given domain address and port. Please, tell me then what is happens.

**Comment by kwek20** [comment]
Closed due to inactivity. Please reopen the ticket if you are still experiencing this.
