### ISSUE TITLE
IotaAPI.java method addRemainder bug

### ISSUE THREAD

**Issue by LionsWang** [iotaledger/iota-java#67]
addRemainder will add the output repeatedly

**Comment by BerserkerInterpreter** [comment]
Please, provide more information about the problem. Show us an example with initial state parameters and the output given by the execution of addRemainder method. Thanks.

**Comment by pinpong** [comment]
@wangzhenhua-bijie
the remainderAddress is always the same while getNewAddress return the same index.

`GetNewAddressResponse res = getNewAddress(seed, security, 0, false, 0, false);`
`String remainderAddress =  res.getAddresses().get(0);`

**Comment by runplay** [comment]
Is this a stateless or state full implementation?

if Stateless
public GetNewAddressResponse getNewAddressfinal String seed, int security, final int index, final boolean checksum, final int total, final boolean returnAll) throws ArgumentException {
if you pass total of 0 (Zero)
then it indicates to process through all Addresses starting at Zero until it finds a free Address. it's just not clear in the comments, suggest change comment
     * @param total     Total number of addresses to generate.
to
     * @param total     Total number of addresses to generate. pass a Zero value for state less wallets


If State full (total=1 or more) then you need to pass the address index in yourself.
GetNewAddressResponse res = getNewAddress(seed, security, 0, false, 1, false);
GetNewAddressResponse res = getNewAddress(seed, security, 1, false, 1, false);
GetNewAddressResponse res = getNewAddress(seed, security, 2, false, 1, false);
GetNewAddressResponse res = getNewAddress(seed, security, 3, false, 1, false);

I do not think this is a bug, more a clarity issue

**Comment by kwek20** [comment]
This has been addressed with the rewrite of getNewAddress in #122
