### ISSUE TITLE
Expand IotaApi.java test coverage for getBundle

### ISSUE THREAD

**Issue by paulhandy** [iotaledger/iota-java#68]
From PR #65, there was a bug in retrieving bundles with a signature size greater than 2. I would recommend, and request, that tests be added to assure that it can handle bundles with arbitrary signature sizes.

**Comment by BartoszMiller** [comment]
I had a look at the project and it is very difficult to unit test any class due to the fact that it is impossible to mock IotaAPIService. Do you think it is a good idea to introduce mock server for tests using e.g. mockserver-netty?
