### ISSUE TITLE
Problem with method "getBundle" which include many transactions (more 100 for example)

### ISSUE THREAD

**Issue by ajet21** [iotaledger/iota-java#77]
When transaction in bundle with many transactions, methods "bundlesFromAddresses" and "getBundle" don`t return this transactions. We have used one of this method instead "findTransactionObjectsByAddresses" because we need "persistance" value (need to know is transaction confirmed). 
Transaction example: "VC9KNL9RQAMPIZ9YGSJZSQCJRXEULQWBFAL9NTPNMDAXFLOLQALNXXLLIAKWZGSXEATFPT9VPHUO99999"

**Comment by runplay** [comment]
once you get the list of Hashes back, you then call 
public GetInclusionStateResponse getLatestInclusion(String[] hashes) throws ArgumentException {

not a bug but a design choice for optimal speed of the system. 

It's the same with the .js library

just create your own calling...
public ... getTranactions(List<Addresses> addesses, boolean includeStates) {
     String[] hashes = findTransactionObjectsByAddresses(....);
     if(includeStates) {
        Result .... getInclusionStates(hashes);
     }
     ///marry then together, both will have a list/array of exact index matches
    return whatEverYourDecided implementation.
}
