### ISSUE TITLE
`Signing` class cannot create old CURL addresses

### ISSUE THREAD

**Issue by schierlm** [iotaledger/iota-java#78]
While the `Signing` class constructor can be used to pass a Curl implementation (both Curl and Kerl) into the class, it cannot be used for generating Curl addresses, as some parts of the class will ignore the passed in Curl implementation but instead create a new one of type Kerl.

Not sure how useful this feature is in practice - it cost me 3 hours of searching why my Curl signatures did not match, though. 

So should we remove the possibility to choose the hash function or make it work?

**Comment by BerserkerInterpreter** [comment]
I think a good aproach to fix the current problem will be this:

`package jota.utils;

import jota.error.ArgumentException;
import jota.model.Bundle;
import jota.model.Transaction;
import jota.pow.ICurl;
import jota.pow.SpongeFactory;
import jota.pow.SpongeFactory.Mode;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static jota.pow.JCurl.HASH_LENGTH;
import static jota.utils.Constants.INVALID_SECURITY_LEVEL_INPUT_ERROR;


public class Signing {
    public final static int KEY_LENGTH = 6561;

    private ICurl curl;

    /**
     * public Signing() {
     * this(null);
     * }
     *
     * /**
     *
     * @param curl
     */
    public Signing(ICurl curl) {
        this.curl = curl;
    }

    /**
     * @param inSeed
     * @param index
     * @param security
     * @return
     * @throws ArgumentException is thrown when the specified security level is not valid.
     */
    public int[] key(final int[] inSeed, final int index, int security) throws ArgumentException {
        if (security < 1) {
            throw new ArgumentException(INVALID_SECURITY_LEVEL_INPUT_ERROR);
        }

        int[] seed = inSeed.clone();

        // Derive subseed.
        for (int i = 0; i < index; i++) {
            for (int j = 0; j < seed.length; j++) {
                if (++seed[j] > 1) {
                    seed[j] = -1;
                } else {
                    break;
                }
            }
        }
        
        ICurl curl = this.evaluateCurlObject();
        curl.absorb(seed, 0, seed.length);
        // seed[0..HASH_LENGTH] contains subseed
        curl.squeeze(seed, 0, seed.length);
        curl.reset();
        // absorb subseed
        curl.absorb(seed, 0, seed.length);

        final int[] key = new int[security * HASH_LENGTH * 27];
        final int[] buffer = new int[seed.length];
        int offset = 0;

        while (security-- > 0) {
            for (int i = 0; i < 27; i++) {
                curl.squeeze(buffer, 0, seed.length);
                System.arraycopy(buffer, 0, key, offset, HASH_LENGTH);

                offset += HASH_LENGTH;
            }
        }
        return key;
    }

    public int[] signatureFragment(int[] normalizedBundleFragment, int[] keyFragment) {
        int[] signatureFragment = keyFragment.clone();

        for (int i = 0; i < 27; i++) {

            for (int j = 0; j < 13 - normalizedBundleFragment[i]; j++) {
                curl.reset()
                        .absorb(signatureFragment, i * HASH_LENGTH, HASH_LENGTH)
                        .squeeze(signatureFragment, i * HASH_LENGTH, HASH_LENGTH);
            }
        }

        return signatureFragment;
    }

    public int[] address(int[] digests) {
        int[] address = new int[HASH_LENGTH];
        ICurl curl = this.evaluateCurlObject();
        curl.reset()
                .absorb(digests)
                .squeeze(address);
        return address;
    }

    public int[] digests(int[] key) {
        int security = (int) Math.floor(key.length / KEY_LENGTH);

        int[] digests = new int[security * HASH_LENGTH];
        int[] keyFragment = new int[KEY_LENGTH];

        ICurl curl = this.evaluateCurlObject();
        for (int i = 0; i < Math.floor(key.length / KEY_LENGTH); i++) {
            System.arraycopy(key, i * KEY_LENGTH, keyFragment, 0, KEY_LENGTH);

            for (int j = 0; j < 27; j++) {
                for (int k = 0; k < 26; k++) {
                    curl.reset()
                            .absorb(keyFragment, j * HASH_LENGTH, HASH_LENGTH)
                            .squeeze(keyFragment, j * HASH_LENGTH, HASH_LENGTH);
                }
            }

            curl.reset();
            curl.absorb(keyFragment, 0, keyFragment.length);
            curl.squeeze(digests, i * HASH_LENGTH, HASH_LENGTH);
        }
        return digests;
    }

    public int[] digest(int[] normalizedBundleFragment, int[] signatureFragment) {
    	ICurl iCurl = this.evaluateDigestCurlObject();
        ICurl jCurl = this.getICurlObject(SpongeFactory.Mode.KERL);
        int[] buffer = new int[HASH_LENGTH];

        for (int i = 0; i < 27; i++) {
            buffer = Arrays.copyOfRange(signatureFragment, i * HASH_LENGTH, (i + 1) * HASH_LENGTH);

            for (int j = normalizedBundleFragment[i] + 13; j-- > 0; ) {
                jCurl.reset();
                jCurl.absorb(buffer);
                jCurl.squeeze(buffer);
            }
            iCurl.absorb(buffer);
        }
        iCurl.squeeze(buffer);

        return buffer;
    }

    public Boolean validateSignatures(Bundle signedBundle, String inputAddress) {
        String bundleHash = "";
        Transaction trx;
        List<String> signatureFragments = new ArrayList<>();

        for (int i = 0; i < signedBundle.getTransactions().size(); i++) {
            trx = signedBundle.getTransactions().get(i);

            if (trx.getAddress().equals(inputAddress)) {
                bundleHash = trx.getBundle();

                // if we reached remainder bundle
                String signatureFragment = trx.getSignatureFragments();
                if (InputValidator.isNinesTrytes(signatureFragment, signatureFragment.length())) {
                    break;
                }
                signatureFragments.add(signatureFragment);
            }
        }

        return validateSignatures(inputAddress, signatureFragments.toArray(new String[signatureFragments.size()]), bundleHash);
    }


    public Boolean validateSignatures(String expectedAddress, String[] signatureFragments, String bundleHash) {

        Bundle bundle = new Bundle();

        int[][] normalizedBundleFragments = new int[3][27];
        int[] normalizedBundleHash = bundle.normalizedBundle(bundleHash);

        // Split hash into 3 fragments
        for (int i = 0; i < 3; i++) {
            normalizedBundleFragments[i] = Arrays.copyOfRange(normalizedBundleHash, i * 27, (i + 1) * 27);
        }

        // Get digests
        int[] digests = new int[signatureFragments.length * HASH_LENGTH];

        for (int i = 0; i < signatureFragments.length; i++) {

            int[] digestBuffer = digest(normalizedBundleFragments[i % 3], Converter.trits(signatureFragments[i]));

            System.arraycopy(digestBuffer, 0, digests, i * HASH_LENGTH, HASH_LENGTH);
        }
        String address = Converter.trytes(address(digests));

        return (expectedAddress.equals(address));
    }
    
    private ICurl getICurlObject(SpongeFactory.Mode mode) {
    	return SpongeFactory.create(mode);
    }
    
    private ICurl evaluateCurlObject() {
    	ICurl iCurl = null;
    	if(this.curl != null) {
        	iCurl = this.curl.clone();
        	iCurl.reset();
        } else {
        	iCurl = this.getICurlObject(Mode.KERL);
        }
    	return iCurl;
    }
    
    private ICurl evaluateDigestCurlObject() {
    	ICurl iCurl = null;
    	if(this.curl != null) {
    		iCurl = this.curl.clone();
    	} else {
    		iCurl = this.getICurlObject(SpongeFactory.Mode.KERL);
    	}
    	return iCurl;
    }
}
`

**Comment by BerserkerInterpreter** [comment]
@schierlm Let me explain. I've created one method which is called evaluateCurlObject, this method is in charge to clone the customized curl object given in the constructor, so that an important problem called "Live Lock Race" is not going to happen, the latter method is called in many parts of this class.  

Another point. The method called "evaluateDigestCurlObject" is a method uniquely used in the method "digest". This method has the responsability to clone the current curl object or getting a curl object of type KERL.

A matter of importance is to avoid the Live Lock Race problem because this stops the advance of the program execution.

**Comment by schierlm** [comment]
My opinion: Is there any use case that **requires** that a single `Signing` object is used concurrently by multiple threads (instead of having one object in each individual thread)? I don't see it. So my approach would be the same as e.g. [SimpleDateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html#synchronization) uses: Document in the Javadoc that one `Signing` object may not be used by multiple threads concurrently.

That being said, cloning the instance like you suggested in [your first comment](https://github.com/iotaledger/iota.lib.java/issues/78#issuecomment-354387613) would solve the problem as well (at the cost of extra allocation of hash instances and their embedded arrays, but that "problem" is also with the current implementation).

**Comment by BerserkerInterpreter** [comment]
@schierlm @pinpong Creo que debemos preparar el sistema para que sea elástico, capaz de enfrentar el escenario cuando hay múltiples hilos usando un método no sincronizado en un objeto. El sistema en un futuro puede necesitar utilizar varios hilos en esta clase (no sé si este escenario existe ahora), el usuario puede quejarse sobre la necesidad de una funcionalidad de concurrencia múltiple.

Cito la especificación de la biblioteca de Java de IOTA:

> ** El envoltorio IOTA Java está diseñado para ser seguro para subprocesos ** y lo más simple posible para que sea fácil de mantener, de acuerdo con la evolución natural en curso de la API de IOTA. Todo el código repetitivo para conectarse a la interfaz REST del nodo se ha ocultado como detalle de implementación (usando Retrofit 2): solo interactuarás con Java puro.

¿Cómo podemos hacer que un hilo de sistema sea seguro? Hay dos posibilidades: usar un bloqueo de todos modos (método sincronizado u objeto de bloqueo) o crear nuevas instancias para permitir que cada hilo itere independientemente sobre la ejecución de los métodos dados.

Creo que el mejor enfoque, mientras tanto, es crear instancias múltiples para evitar cualquier tipo de disputa sobre los métodos respectivos para ejecutar.

**Comment by BerserkerInterpreter** [comment]
@schierlm @pinpong I think we should prepare the system to be elastic, able to face the scenario when there are multiple threads using an unsynchronized method in an object. The system in the future may need to use several threads in this class (I do not know if this scenario exists now), the user may complain about the need for multiple concurrency functionality.

I quote the specification of the IOTA Java library:

> ** The IOTA Java wrapper is designed to be thread-safe ** and as simple as possible so that it is easy to maintain, according to the ongoing natural evolution of the IOTA API. All the repetitive code to connect to the REST interface of the node has been hidden as implementation detail (using Retrofit 2): you will only interact with pure Java.

How can we make a system thread secure? There are two possibilities: use a lock in anyway (synchronized method or block object) or create new instances to allow each thread to iterate independently on the execution of the given methods.

I think the best approach, meanwhile, is to create multiple instances to avoid any kind of contentio over the respective methods to execute.
