### ISSUE TITLE
Can not send a transaction, 

### ISSUE THREAD

**Issue by majorVitos** [iotaledger/iota-java#82]
I used iota java library 0.9.11

and got an exception

> jota.error.ArgumentException: [{"error":"starting tip failed consistency check: VAZRZILTVSZKOELMJSHTBHHUYJZON9LRBYMCDBKZMKXIKFVTRVZFEGXJXSRXBEPOUVFESMDBCYYC99999","duration":1474}]
	at jota.IotaAPICore.wrapCheckedException(IotaAPICore.java:71)
	at jota.IotaAPICore.getTransactionsToApprove(IotaAPICore.java:303)
	at jota.IotaAPI.sendTrytes(IotaAPI.java:236)
	at jota.IotaAPI.sendTransfer(IotaAPI.java:825)
	at iotatest.test1.shouldSendTransfer(test1.java:72)
	at iotatest.IotaTest.main(IotaTest.java:39)

with code

IotaAPI api = new IotaAPI.Builder()
            .localPoW(new PearlDiverLocalPoW())
            .protocol("http")
            .host("eugene.iota.community")
            .port("14265")
            .build();

        String seed = "seed";
        String tag2 = "UPDATE999999999999999999999";
        String sendToAddress = "NYYVQVJMQVYCB9AQXTYFQOZP99R9GRIYRJV9MYIJKTBNXRMAGDXJQWYFKCXBPRLRPBZRRHRZOZTFEWJXBIRWEEGCTW";
        List<Transfer> transfers = new ArrayList<>();
        transfers.add(new jota.model.Transfer(sendToAddress, 0, "ATTACH", tag2));
        jota.dto.response.SendTransferResponse str = api.sendTransfer(seed, 2, 5, 14, transfers, null, null, false, false);
        System.out.println(java.util.Arrays.toString(str.getSuccessfully()));

**Comment by majorVitos** [comment]
Same on node.js with iota.lib.js. eugene.iota.community is the only one node with enabled attachToTangle except android wallet default node. On android node it is works fine.

**Comment by runplay** [comment]
This happens (at least in one case) when the IRI node is out of sync with the tangle, which happens for a very very short period when a new milestone is published.

Solution is to catch and test this exception and re-try transfer again... nothing the jota library can or should really do, possibly catch it itself and then call getTransactionsToApprove(depth); again.

Basically IRI has provided the tips from the last milestone, or at least to my knowledge.

**Comment by kwek20** [comment]
What @runplay said is correct.
If you still think we should handle this, just reply with your motivation behind this.

I will close this issue otherwise.
